import com.bmuschko.gradle.tomcat.extension.TomcatPluginExtension
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0.1/userguide/tutorial_java_projects.html
 */
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath("com.bmuschko:gradle-tomcat-plugin:2.5")

    }
}

plugins {
    // Apply the java plugin to add support for Java
    java
    war
    idea
    id("com.bmuschko.tomcat") version "2.5"
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    jcenter()
}

sourceSets {
    main {
        java.srcDir("src/main/java")
        java.srcDir("src/main/kotlin")
        resources.srcDir("src/main/resources")
    }
    test {
        java.srcDir("src/test/java")
        java.srcDir("src/test/kotlin")
        resources.srcDir("src/main/resources")
    }
}

dependencies {
    val springVersion = "5.2.2.RELEASE"
    val springDataVersion = "2.2.3.RELEASE"
    val hibernateVersion = "5.4.10.Final"
    val tomcatVersion = "9.0.1"
    implementation("org.springframework:spring-webmvc:$springVersion")
    implementation("org.springframework.data:spring-data-jpa:$springDataVersion")

    implementation("org.apache.commons:commons-dbcp2:2.7.0")
    implementation("org.hibernate:hibernate-core:$hibernateVersion")
    implementation("org.hibernate:hibernate-entitymanager:$hibernateVersion")

    implementation("com.h2database:h2:1.4.200")

    tomcat("org.apache.tomcat.embed:tomcat-embed-core:$tomcatVersion")
    tomcat("org.apache.tomcat.embed:tomcat-embed-logging-juli:9.0.0.M6")
    tomcat("org.apache.tomcat.embed:tomcat-embed-jasper:$tomcatVersion")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:28.0-jre")

    implementation("org.slf4j:slf4j-api:1.7.30")
    implementation("org.slf4j:slf4j-log4j12:1.7.30")

//    implementation("org.apache.commons:commons-dbcp2:2.6.0")
//    implementation("commons-io:commons-io:2.6")

    implementation("javax.servlet:javax.servlet-api:3.1.0")
    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

configure<TomcatPluginExtension> {
    httpProtocol = "org.apache.coyote.http11.Http11Nio2Protocol"
    ajpProtocol = "org.apache.coyote.ajp.AjpNio2Protocol"
}