/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.mbbn.core;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan("ir.mbbn.core")
public class AppConfig {
}
